version: "3"
services:
  mydb:
    build:
      context: ./dockerfile/mysql8
    container_name: mydb
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${DATA_DIR}/mysql:/var/lib/mysql/:rw
      - ${MYSQL_RUN_FILE}/mysqld:/var/run/mysqld/:rw
      - ./logs/mysql:/var/log/mysql
      - ./data/mysql:/data/mysqlback
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: Asia/Shanghai
    networks:
      - default

  myredis:
    build:
      context: ./dockerfile/redis
      args:
        TZ: Asia/Shanghai
    container_name: myredis
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
      - ${DATA_DIR}/redis:/data/:rw
    restart: always
    entrypoint: [ "redis-server", "/etc/redis.conf" ]
    environment:
      TZ: Asia/Shanghai
    networks:
      - default

  myphp:
    build:
      context: ./dockerfile/php8
      args:
        TZ: Asia/Shanghai
    container_name: myphp
    expose:
      - 9501
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${DATA_DIR}/php:/usr/local/etc/php
      - ${LOG_DIR}/php:/var/log/php
    restart: always
    links:
      - mydb
      - myredis
    cap_add:
      - SYS_PTRACE
    networks:
      - default


  mynginx:
    build:
      context: ./dockerfile/nginx
    container_name: mynginx
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    links:
      - "myphp"
    volumes:
      - ${SOURCE_DIR}:/usr/share/nginx/html
      - ${NGINX_CONFD_DIR}/conf.d/:/etc/nginx/conf.d/:rw
      - ${NGINX_CONFD_DIR}/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${LOG_DIR}/nginx:/var/log/nginx
    environment:
      TZ: Asia/Shanghai
    restart: always
    networks:
      - default
